#!/bin/python3
#coding: utf-8

import os
import glob


file=glob.glob('*.*')
print("Na pasta actual existem os seguintes ficheiros: ", file)

file=glob.glob('*.py')
print("Na pasta actual existem os seguintes ficheiros em python: ", file)

ficheiro = open("lista.txt", 'w')
ficheiro.write(str(file))
ficheiro.close()
