#!/bin/python3
#coding: utf-8

import os 
import ipaddress

#a) 

conjuntoip=ipaddress.IPv4Network('192.168.1.0/29')
  listacinq = [ ]
    print ("alinea a")

for ip in conjuntoip:
    sinal = os.system("ping -c 1 " + str(ip) + " > /dev/null 2>&1")
      if sinal == 0:
          listacinq.append(f'{ip}')

listacinq=listacinq[:2]
  print (listacinq)


# b) 

print ("alinea b")

def imprip ():
    for ip in listacinq:
        print (f'{ip}')

imprip ()
