#!/bin/python3

import os 
import ipaddress
from getmac import get_mac_address


print ("Alinea a)")
conjuntoip=ipaddress.IPv4Network('192.168.3.0/24')
for ip in conjuntoip:
    print(f'{ip}')


print ("Alinea b) e d)")
rede=input("Indique qual é o endereço de rede em formato CIDR (ex. 192.168.1.0/24): ")
ipdomestico=ipaddress.IPv4Network(rede)

for ips in ipdomestico:
    sinal = os.system("ping -c 1 " + str(ips) + " > /dev/null 2>&1")
    if sinal == 0:
        print("O endereço de IP " + (f'{ips}') + " está ligado.")
        print("O endereço MAC é " + get_mac_address(ip=sinal, network_request=True))
    else:
        print("O endereço de IP " + (f'{ips}') + " está desligado.")



print("Nome de utilizador atualmente com sessão iniciada: ", os.getenv('LOGNAME'))
